Create-Header- footer
AnsarIbrahim/Protfolio-finish-mobileversion pull request #2
Opened 2023-01-20 15:00 UTC by AnsarIbrahim

### This PR adds the following sections :
- header
- tagline
- main
- contant
- footer

2023-01-20 17:18 UTC, NduatiKagiri requested changes
Hi @AnsarIbrahim 👋 ,

# CHANGES REQUIRED ♻️  

You have implemented the project requirements with a wrong approach.
There are some issues that you still need to work on to go to the next project.

## Highlights ✔️ 
✅ No Linters errors
✅ GitHub Flow observed
✅ Good PR description

## Required Changes ♻️

- [ ] You have taken screenshots of the Figma design and loaded them on your page as images. Kindly add everything on the page using its respective elements, as guided in the comments. Only add the required images or icons using the `img` element.
- [ ] Please make sure that everything from the previous milestones of this project is still working correctly, as I can see too many errors in the header and the headline.
- [ ] Kindly check that your page fits in the mobile screen since it is currently overflowing causing a horizontal scroll.

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 17:18 UTC, NduatiKagiri commented on index.html
> +            <img src="assest/img/aboutme/Enable.png" alt="resume-img">
- [ ] 'Get My Resume' should be added as a button or an anchor tag since it is supposed to take some action on the page, or redirect the user. Please make that change.

2023-01-20 17:18 UTC, NduatiKagiri commented on index.html
> +            <img src="assest/img/aboutme/card/Card Works.Inactive (2).png" alt="skill-img">
- [ ] You have taken screenshots of the Technologies cards on the Figma template and added the images on your page which is a wrong way of implementing the project requirements. Kindly add everything from the design to the page separately using the required elements e.g. `hx` for headings, `p` for texts, `img` / `i` for icons, and `div` for card containers. Remember that these technologies should be added as lists(using the `ul` element), and each should be a list item in the list(added using the `li` element).

2023-01-20 17:18 UTC, NduatiKagiri commented on index.html
> +        <div class="info"><img src="assest/img/last/Form.png" alt="last-img"></div>
- [ ] You have taken a screenshot of the Contact Form on the Figma template and added the image on your page which is a wrong way of implementing the project requirements. Kindly add everything from the form in the design to the page separately using the required elements e.g. `form` for form container, `input` for form inputs, `textarea` for text areas, and `button` for buttons.

2023-01-21 12:00 UTC, closed without merging

2023-01-21 19:32 UTC, Kamba56 reviewed
Hi @AnsarIbrahim

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **has a closed PR**. Linters cannot run on a closed PR. Kindly re-open the PR and request for a re-review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-21 20:36 UTC, iambenkis reviewed
> Hi @AnsarIbrahim
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that **has a closed PR**. Linters cannot run on a closed PR. Kindly re-open the PR and request for a re-review.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._